extern void spi0_init(void);
extern unsigned char spi0(unsigned char data);
extern unsigned int mcp3204_adc_read(unsigned char ch_num);
extern void lcd_data(unsigned char data);
extern void lcd_cmd(unsigned char cmd);
extern void lcd_init(void);
extern void lcd_string(char *ptr);
extern void lcd_integer(int num);
extern void lcd_float(float f);
extern void delay_sec(unsigned int sec);
extern void delay_ms(unsigned int ms);
extern void uart0_init(unsigned int baud); 
extern void uart0_tx(unsigned char data);
extern unsigned char uart0_rx(void);
extern void uart0_tx_integer(int num);
extern void uart0_rx_string(char *ptr,int len);
extern void uart0_tx_string(char *ptr);
extern void adc_init(void);
extern unsigned int adc_read(int ch_num);
extern void uart0_tx_float(float num);
extern void Potentiometer(void);
extern void Temperature(void);
extern void LDR(void);
extern float Intensity;
